[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_TIMEOUT = "10000"
  REACT_APP_UPDATE_INTERVAL = "30000"
  REACT_APP_DEMO_MODE = "true"
  REACT_APP_VERSION = "2.1.1-enhanced"
  ESLINT_NO_DEV_ERRORS = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"